### ISSUE TITLE
Moving object tracking

### ISSUE THREAD

**Issue by yuninn** [tensorturtle/classy-sort-yolov5#4]
Hello, I use yolov5 to detect moving vehicles,and I don’t detect stationary vehicles, so when the target moves from motion to static to motion, the tracking will be lost. Is there any good solution?

**Comment by tensorturtle** [comment]
If the track ID is being lost because of rapid motion, you can do two things.
1. Decrease SORT IOU threshold argument. For example, `classy-track.py --sort-iou-thresh 0.1`
2. Increase SORT Kalman Filter process noise coefficient. In `SORT/sort.py` line 122,  change 0.5 to something higher: `self.kf.Q[-1,-1] *= 0.5 # Q: Covariance matrix of process noise (set to high for erratically moving things)`

**Comment by yuninn** [comment]
> If the track ID is being lost because of rapid motion, you can do two things.
> 
> 1. Decrease SORT IOU threshold argument. For example, `classy-track.py --sort-iou-thresh 0.1`
> 2. Increase SORT Kalman Filter process noise coefficient. In `SORT/sort.py` line 122,  change 0.5 to something higher: `self.kf.Q[-1,-1] *= 0.5 # Q: Covariance matrix of process noise (set to high for erratically moving things)`

Thank you for your help, the effect is much better！

**Comment by ingbeeedd** [comment]
@tensorturtle 
What is the problem with the id changing of the objects that are stationary ?
`sort-max-age` param is also set long, but this is the problem.

**Comment by tensorturtle** [comment]
Hi @ingbeeedd Tracking can't be expected to have perfect accuracy, and unfortunately there may be id switches even on stationary objects, although that should be rare. If you need more help, send me a sample video output and I can take a look.

**Comment by ingbeeedd** [comment]
@tensorturtle 
Where should I send it?

**Comment by tensorturtle** [comment]
@ingbeeedd You could upload it to youtube as an unlisted video and comment the link, or send it to tensorturtle@gmail.com
